### ISSUE TITLE
Fernflower changing field/variable names to a unicode snowman?

### ISSUE THREAD

**Issue by PizzaCrust** [LapisBlue/Nocturne#12]
I see some FernFlower issues that haven't been fixed in this tool such as fernflower replacing parameter names with this (snowman?):
![parametervariableissue](https://cloud.githubusercontent.com/assets/15954148/13314345/540d5252-dbd7-11e5-805a-c1cc0081f674.PNG)

**Comment by caseif** [comment]
This is something specific to Minecraft, wherein the obfuscator sets parameter/local variable names to a Unicode snowman. I'll try to fix this specific case at least for the 1.0 release.

**Comment by caseif** [comment]
I've implemented a fix for this issue. However, it's very rushed and will likely be improved in the future. Therefore, I've opened #13 to track this.
