### ISSUE TITLE
Allow manual toggling of whether a member is deobfuscated

### ISSUE THREAD

**Issue by caseif** [LapisBlue/Nocturne#17]
Certain members (especially those defined by a superclass or interface) may already have a sensible name. Therefore, Nocturne should permit users to manually toggle whether a member is considered "deobfuscated" via a context menu item.

**Comment by jamierocks** [comment]
Would we produce
```CL:

**Comment by caseif** [comment]
Not really sure. It wouldn't persist across sessions so I need to figure out how we should implement it.

**Comment by jamierocks** [comment]
Is this resolved?

**Comment by caseif** [comment]
Yes, forgot to mention it in the commit message. da83818 and bd2da86, for reference.
