### ISSUE TITLE
Repackaging Classes

### ISSUE THREAD

**Issue by phase** [LapisBlue/Nocturne#20]
Selecting a class' package should allow you to change it. For me, this can help when moving Spigot's mappings into new packages.

**Comment by jamierocks** [comment]
This was a feature I've thought of adding. I decided against it because you can just as easily do it from the class name. But seeing as it's been mentioned I may well look into this.

**Comment by caseif** [comment]
Marking as wontfix for now. I considered making `package` statements selectable for 1.0, but decided the implementation would be too complex to justify writing given that this is a relatively minor feature. However, I may revisit this issues at some point in the future if I change my mind after more urgent issues have been resolved.
