### ISSUE TITLE
Support for Procyon

### ISSUE THREAD

**Issue by jamierocks** [LapisBlue/Nocturne#23]
Support using both FernFlower and Procyon

**Comment by caseif** [comment]
Ehh... we currently have a whole suite of patches in place to make it possible for FernFlower to work with our class transforming system. Is it really worth the trouble of getting Procyon working with it as well?

**Comment by jamierocks** [comment]
I completely forgot about our class processing :s

Seeing as this may benefit me I'll take a look at doing this when I get back.

**Comment by phase** [comment]
Being able to switch between a host of decompilers would be a really cool feature. Seeing the different ways complex code can be decompile can help with figuring out its meaning.

**Comment by chibill** [comment]
Yeah. But see as Procyon choked on obfuscated code a lot it migh not be useful.

**Comment by jamierocks** [comment]
Though it would be nice to do this, IMO the effort is too great. Procyon, like an un-patched FernFlower, will choke on newer Minecraft versions.
