### ISSUE TITLE
Split project into modules

### ISSUE THREAD

**Issue by jamierocks** [LapisBlue/Nocturne#31]
We have fantastic code in various parts of Nocturne, and its a shame that others aren't able to use some of the fantastic engineering we have done.

For me a good example of this is: mappings - a good use of this could be a simple converter program.

This may also be good to lay the groundwork for #11.

**Comment by caseif** [comment]
Good idea. Only commentary is we should keep this within a feature branch for the time being, since it's a fairly major change/refactor.
