### ISSUE TITLE
Few app classes missing (name issue ?)

### ISSUE THREAD

**Issue by lemonsqueeze** [LapisBlue/Nocturne#32]
Hi,

Playing around with an app in Nocturne the other day i noticed something strange :  
A few of the app classes were missing from the "Obfuscated Classes" tree on the left, and couldn't be reached either through other classes using them as fields (class shows up black instead of red where "Jump to defining class" normally works).

At first I thought fernflower might have a problem with these, but when i tried one of them in isolation in a jar of its own the class showed up no problem in Nocturne. Looked like some other class was interfering or something. Searching the other classes, there is indeed one completely unrelated class which triggers the bug. Even stripping out all the code it still happens.

Here's the simplest test case i got so far: 
[test.zip](https://github.com/LapisBlue/Nocturne/files/1010338/test.zip)

**bad.jar:** 2 classes `fg` and `gH`, but `fg` doesn't show up.
**good.jar:** same with class `gH` renamed to `gh`. Now it works.
.j files are disassembled class files from krakatau, these classes are pretty much empty.

Tested with v1.1.0 release.

**Comment by caseif** [comment]
Hm, didn't notice this until now. Probably an issue with the indexing or something; I think I recall seeing a similar bug before.

**Comment by caseif** [comment]
Seems that "fg" and "gH" have the same hashcode per the JSL implementation. Very odd indeed.

**Comment by caseif** [comment]
Fixed in 1.1.2.
