### ISSUE TITLE
Enigma reader fails on parameter mappings

### ISSUE THREAD

**Issue by jamierocks** [LapisBlue/Nocturne#38]
The Enigma reader will incorrect pop the class stack when reading method mappings with parameter mappings.

**Comment by jamierocks** [comment]
@MGlolenstine just a quick update, I've begun working on our Enigma support so that we output as close to Enigma as possible. You can see this work on the [hotfix-1.1.4 branch](https://github.com/LapisBlue/Nocturne/compare/hotfix-1.1.4).

I will try make such update as soon as possible, however I've unfortunately unearthed further issues that are going to requre further work.

**Comment by jamierocks** [comment]
There remains to be an issue with array types, that I haven't been able to identify the source of. However, the output from Nocturne is now far improved (outputting in the same order, etc) - see https://gist.github.com/jamierocks/b1fd0b6b879c6394028ab49493883434/revisions#diff-3b9f3fa0b2b0293150ba07c2d12586f9 for the current differences.

(do note that there are still issues with that diff, that I'm working on)

**Comment by caseif** [comment]
The issue of array tokens being dropped should be resolved - it was caused by Nocturne incorrectly processing `Type` instances when appending the `none` prefix required by Enigma mappings.

**Comment by jamierocks** [comment]
For reference, https://github.com/LapisBlue/Nocturne/commit/d36e3f2313bfeccda80338a056f5bf91e540b0d7 is the commit referenced above.

We'll leave it a short while before making the release, but we'll try to make it within the next week.

**Comment by jamierocks** [comment]
Resolved with https://github.com/LapisBlue/Nocturne/releases/tag/1.1.4
