### ISSUE TITLE
Mappings should not be immutable

### ISSUE THREAD

**Issue by caseif** [LapisBlue/Nocturne#7]
Mappings should not be immutable, as their deobfuscated name can change. It makes more sense to manipulate an existing mapping than to create an entirely new one. Furthermore, introduction of this change would solve several bugs which would otherwise need to be fixed explicitly, such as member mappings not being carried between class renaming.

**Comment by caseif** [comment]
Working on this now, will commit it either tonight or tomorrow (@jamierocks pls don't touch :smile:).

**Comment by jamierocks** [comment]
Okay that's cool it's 11:51pm over here anyway so you needn't worry ;)
